image: node:8.17.0

pipelines:
  custom: # Pipelines that are triggered manually
    build_js:
      - step:
         name: "Build the JS modules"
         caches:
           - node
         script:
           - npm install
           - npm install -g grunt-cli
           - grunt --verbose shifter
           - ls -altR yui/build/
