image: node:8.17.0

definitions:
  caches:
#    node: node_modules
    apt: /var/cache/apt

pipelines:
  #custom: # Pipelines that are triggered manually
    #build_js:
  tags:
    '*':
      - step:
         name: "Build the JS modules"
         caches:
           - node
           - apt
         script:
           - apt-get update && apt-get -qq install zip rsync
           - mkdir -p /tmp/iaparent/integrityadvocate
           - rsync -av ./ /tmp/iaparent/integrityadvocate --exclude *.pl --exclude *.zip --exclude .git/ --exclude .gitignore --exclude Makefile --exclude bitbucket-pipelines.yml --exclude screenshots/ --exclude tests/
           - cd /tmp/iaparent/integrityadvocate
           #- ls -altrh
           - npm install
           - npm install -g grunt-cli
           - grunt --verbose shifter
           #- cat yui/build/${BITBUCKET_REPO_SLUG}-form/${BITBUCKET_REPO_SLUG}-form-min.js
           - find ./ \( -type d -name .git -prune \) -o -type f -name '*.php' -print0 |  xargs -0 sed -i 's#$debug = true;#$debug = false;#g'
           - cd /tmp/iaparent/
           #- ls -altrh
           - find . -empty -type d -delete #Moodle installer fails on empty dirs
           - zip -r9 ${BITBUCKET_CLONE_DIR}/${BITBUCKET_REPO_SLUG}.zip ./ -x **/node_modules/**\* -x **/node_modules/\* Gruntfile.js \*.yml
           - curl -vvvv -s -u "${BB_AUTH_STRING}" -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files="@${BITBUCKET_CLONE_DIR}/${BITBUCKET_REPO_SLUG}.zip"
