image: node:8.17.0

pipelines:
  custom: # Pipelines that are triggered manually
    build_js:
      - step:
         name: "Build the JS modules"
         caches:
           - node
         script:
           - curl -vvvv -s https://raw.githubusercontent.com/moodle/moodle/MOODLE_38_STABLE/Gruntfile.js --output Gruntfile.js
           - npm install
           - npm install -g grunt-cli
           - grunt --verbose shifter
           - ls -altR yui/build/
