# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
#image: php:7.4.2
image: node:13.12.0

#definitions:
#  caches:
#    apt: /var/cache/apt

pipelines:
  custom: # Pipelines that are triggered manually
    build_js:
      - step:
         name: "Build the JS modules"
         caches:
           - node
         script:
           - cd yui/src/form/
           - curl -vvvv -s https://raw.githubusercontent.com/moodle/moodle/MOODLE_38_STABLE/Gruntfile.js --output Gruntfile.js
           - npm install
           #Old <M2.9 Shifter method: - npm install shifter@0.4.6 -g
           - npm install -g grunt-cli
           - grunt shifter --verbose
