image: node:8.17.0

definitions:
  caches:
#    node: node_modules
    apt: /var/cache/apt

pipelines:
  custom: # Pipelines that are triggered manually
    build_js:
      - step:
         name: "Build the JS modules"
         caches:
           - node
           - apt
         script:
           - apt-get update && apt-get -qq install zip
           - npm install
           - npm install -g grunt-cli
           - grunt --verbose shifter
           #- ls -altR yui/build/
           #- cat yui/build/moodle-availability_integrityadvocate-form/moodle-availability_integrityadvocate-form-min.js
           #- find ./ \( -type d -name .git -prune \) -o -type f -name '*.php' -print0 |  xargs -0 sed -i 's#$debug = true;#$debug = false;#g'
           - zip -r9 ${BITBUCKET_CLONE_DIR}/${BITBUCKET_REPO_SLUG}.zip ./ -x .git node_modules .git/**\* node_modules/**\* .gitignore Gruntfile.js \*.yml \*.json
           - curl -vvvv -s -u "${BB_AUTH_STRING}" -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files="@${BITBUCKET_CLONE_DIR}/${BITBUCKET_REPO_SLUG}.zip"


