name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: []
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was triggered by a ${{ github.event_name }} event"
      - run: echo "The name of your branch is ${{ github.ref }}
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          pluginver=$(fgrep 'version =' version.php | cut -f3 -d' ' | tr -d ';')
          echo "Found pluginver=$pluginver"
          
          # Make a folder that we will zip up.
          mkdir -p /tmp/iaparent/integrityadvocate
          # Copy stuff over to the dir to be zipped but skip stuff not needed by Moodle.
          #rsync -av ./ /tmp/iaparent/integrityadvocate --exclude *.pl --exclude *.zip --exclude .git/ --exclude .gitignore --exclude .shifter.json --exclude bitbucket-pipelines.yml --exclude cypress.json --exclude Makefile --exclude phpstan.neon --exclude README_DEVELOPER.txt --exclude workspace.code-workspace --exclude screenshots/ --exclude tests/ --exclude vendor/bin/
          cd /tmp/iaparent/integrityadvocate
          # Debug: 
          ls -altrh
          zipfilepath="${GITHUB_WORKSPACE}/${GITHUB_REPOSITORY##*/}.zip"
          echo "Found zipfilepath=$zipfilepath"
